services:
  server:
    image: ghcr.io/bluewave-labs/checkmate-backend-mono:${VERSION}
    restart: always
    #ports:
    #  - "52345:52345"
    environment:
      - UPTIME_APP_API_BASE_URL=${UPTIME_APP_API_BASE_URL} #http://localhost:52345/api/v1
      - UPTIME_APP_CLIENT_HOST=${UPTIME_APP_CLIENT_HOST} #http://localhost
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db
      - CLIENT_HOST=${CLIENT_HOST} #http://localhost
      - JWT_SECRET=${JWT_SECRET} #my_secret
    depends_on:
      - mongodb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nginx

  mongodb:
    image: ghcr.io/bluewave-labs/checkmate-mongo:${VERSION}
    restart: always
    command: ["mongod", "--quiet", "--bind_ip_all"]
    volumes:
      - ${MONGO_PATH}:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet"]
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    networks:
      - nginx

networks:
  nginx:
    external: true