version: '3.8'

services:
  registry:
    build: .
    #ports:
    #  - "5000:5000"
    environment:
      REGISTRY_USER: ${REGISTRY_USER}
      REGISTRY_PASS: ${REGISTRY_PASS}
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - ${REGISTRY_VOLUME_PATH}:/var/lib/registry
    networks:
      - nginx

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    ports:
      - "9090:80"
    environment:
      - REGISTRY_TITLE=Seamlessideas Docker Registry
      - NGINX_PROXY_PASS_URL=${NGINX_PROXY_PASS_URL}
      - DELETE_IMAGES=true   # enable delete from UI
    depends_on:
      - registry

networks:
  nginx:
    external: true
