services:
  pgbackweb:
    image: eduardolat/pgbackweb:latest
    #ports:
    #  - "8085:8085" # Access the web interface at http://localhost:8085 commented since using npm
    #volumes:
    #  - ./backups:/backups # If you only use S3 destinations, you don't need this volume
    environment:
      PBW_ENCRYPTION_KEY: ${PBW_ENCRYPTION_KEY} # Change this to a strong key
      PBW_POSTGRES_CONN_STRING: ${PBW_POSTGRES_CONN_STRING}
      TZ: ${TZ} # Set your timezone, optional
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nginx
      - default

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # i need this to access via vpn
    volumes:
      - ./home/afaqjaved/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default
      - shared_postgres

networks:
  nginx:
    external: true
  shared_postgres:
    external: true