version: '3.8'

services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'     # Public HTTP Port
      - '443:443'   # Public HTTPS Port
      - '81:81'     # Admin Web Port
    environment:
      DB_MYSQL_HOST: "mariadb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "mariadb"
      DB_MYSQL_PASSWORD: "admin"
      DB_MYSQL_NAME: "nginx-reverse-proxy"
      INITIAL_ADMIN_EMAIL: ${INITIAL_ADMIN_EMAIL}
      INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD}
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - mariadb
    networks:
      - nginx

  mariadb:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "nginx-reverse-proxy"
      MYSQL_USER: "mariadb"
      MYSQL_PASSWORD: "admin"
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - nginx

# No need to define external networks unless you really need to share across projects

networks:
  nginx:
    external: true
